---
- name: Create Nginx configuration directory
  become: true
  ansible.builtin.file:
    path: "{{ apps_folder }}/searchengine/nginx/conf.d"
    state: directory
    owner: nginx
    group: nginx
    mode: 0755
  changed_when: false

- name: Create Nginx log directory
  become: true
  ansible.builtin.file:
    path: "{{ apps_folder }}/searchengine/nginx/log"
    state: directory
    owner: nginx
    group: nginx
    mode: 0755
  changed_when: false

- name:  Copy serachengine Nginx config
  become: true
  ansible.builtin.template:
    dest: "{{ apps_folder }}/searchengine/nginx/conf.d/searchengine.conf"
    src: searchengine.conf.j2
    owner: nginx
    group: nginx
    mode: 0644
  changed_when: false

- name: Run Nginx container
  become: true
  community.docker.docker_container:
    name: searchengine-nginx-container
    image: nginx:latest
    published_ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{ apps_folder }}/searchengine/nginx/conf.d/:/etc/nginx/conf.d"
      - "{{ apps_folder }}/searchengine/nginx/log:/var/log/nginx"
    state: started
    restart_policy: always
    networks:
      - name: "searchengine-net"


