---

- name: Create redis data directory
  become: yes
  ansible.builtin.file:
    path: "{{ apps_folder }}/searchengine/data_dump/redis"
    state: directory
    # User id in elasticsearch Docker image
    owner: 1000
    group: root
    mode: 0700
  changed_when: false

- name: Create Searchengine Redis container
  community.docker.docker_container:
    name: my-redis-container
    image: redis:latest
    networks:
      - name: searchengine-net
        ipv4_address: 10.11.0.22
    # network_mode: "host"
    published_ports:
      - "6379:6379"
    volumes:
      - "{{ apps_folder }}/searchengine/data_dump/redis:/var/lib/redis"
    restart_policy: always