---
# Configure and run search Engine

- name: Get info about the searchengine container
  community.docker.docker_container_info:
    name: searchengine
  register: container_info_searchengine_f

- name: Debug search container state
  ansible.builtin.debug:
    msg: "Container '{{ container_info_searchengine_f }}' is in state: {{ container_info_searchengine_f.exists}}"

- name: set elasticsearch_nodes_urls
  ansible.builtin.set_fact:
    elasticsearch_nodes_urls: []


- name: Create searchengine folder directory
  become: yes
  file:
    path: "{{ apps_folder }}/searchengine/searchengine"
    recurse: yes
    state: directory
    owner: 1000
    group: root
    mode: 0755
  when: not container_info_searchengine_f.exists

- name: Create searchengine logs directory
  become: yes
  file:
    path: "{{ apps_folder }}/searchengine/searchengine/logs"
    state: directory
    owner: 1000
    group: root
    mode: 0755

- name: Create searchengine data_dump directory
  become: yes
  file:
    path: "{{ apps_folder }}/data_dump/{{ default_datasource }}"
    state: directory
    owner: 1000
    group: root
    mode: 0755

- name: Create searchengine cached directory
  become: yes
  file:
    path: "{{ apps_folder }}/searchengine/searchengine/cacheddata"
    state: directory
    owner: 1000
    group: root
    mode: 0755

#Add all elasticsearch nodes
- name: Add elastic nodes to elasticsearch_nodes_urls
  set_fact:
    elasticsearch_nodes_urls: '{{ elasticsearch_nodes_urls + ["https://10.11.0."+item+":9200"] }}'
  with_sequence: start=2 count={{ elasticsearch_no_nodes }}

- name: configure elasticsearch backup folder for docker searchengine
  become: yes
  community.docker.docker_container:
    image: "{{ searchengine_docker_image }}"
    name: searchengine_elasticsearch
    cleanup: True
    command: "set_elasticsearch_backup_folder -b {{ elasticsearch_backup_folder }}"
    state: started
    auto_remove: yes
    volumes:
    - "{{ apps_folder }}/searchengine/searchengine/:/etc/searchengine/"
  changed_when: false

- name: configure elasticsearch for docker searchengine
  become: yes
  community.docker.docker_container:
    image: "{{ searchengine_docker_image }}"
    name: searchengine_elasticsearch
    cleanup: True
    command: "set_elasticsearch_configuration -e {{ elasticsearch_nodes_urls | join(',') }}"
    state: started
    auto_remove: yes
    volumes:
      - "{{ apps_folder }}/searchengine/searchengine/:/etc/searchengine/"
  changed_when: false

- name: configure database for docker searchengine
  become: yes
  community.docker.docker_container:
    image: "{{ searchengine_docker_image }}"
    name: searchengine_database
    cleanup: True
    auto_remove: yes
    #auto_remove: yes
    command: >
      set_database_configuration -d {{ database_name }} -s {{ database_port }} -n {{ database_username }} -p {{ database_user_password }} -b {{ apps_folder }} -w {{ default_datasource }} -u {{ database_server_url }}
    #networks::
    #- name: searchengine-net
    #published_ports:
    #- "5577:5577"
    state: started
    volumes:
    - "{{ apps_folder }}/searchengine/searchengine/:/etc/searchengine/"
  changed_when: false

- name: set default data source
  become: yes
  community.docker.docker_container:
    image: "{{ searchengine_docker_image }}"
    name: searchengine_database
    cleanup: True
    auto_remove: yes
    command: >
      set_default_datasource -d  {{ default_datasource }}
    state: started
    volumes:
      - "{{ apps_folder }}/searchengine/searchengine/:/etc/searchengine/"
  changed_when: false

- name: configure IDR_TEST_FILE_URL item
  become: yes
  community.docker.docker_container:
    image: "{{ searchengine_docker_image }}"
    name: searchengine_IDR_TEST_FILE
    cleanup: True
    auto_remove: yes
    command: "set_idr_test_file -i {{ IDR_TEST_FILE_URL }}"
    state: started
    volumes:
    - "{{ apps_folder }}/searchengine/searchengine/:/etc/searchengine/"
  changed_when: false

- name: configure cache folder  for docker searchengine
  become: yes
  community.docker.docker_container:
    image: "{{ searchengine_docker_image }}"
    name: searchengine_cache
    cleanup: True
    auto_remove: yes
    command: "set_cache_folder -c /etc/searchengine/cachedata"
    #networks:
    #- name: searchengine-net
    #published_ports:
    #- "5577:5577"
    state: started
    volumes:
    - "{{ apps_folder }}/searchengine/searchengine/:/etc/searchengine/"
  changed_when: false

- name: configure number of cache rows for docker searchengine
  become: yes
  community.docker.docker_container:
    image: "{{ searchengine_docker_image }}"
    name: searchengine_cache
    cleanup: True
    auto_remove: yes
    #auto_remove: yes
    command: "set_cache_rows_number -n {{ cache_rows }}"
    state: started
    volumes:
    - "{{ apps_folder }}/searchengine/searchengine/:/etc/searchengine/"
  changed_when: false

- name: configure secret key for docker searchengine
  become: yes
  community.docker.docker_container:
    image: "{{ searchengine_docker_image }}"
    name: searchengine_cache
    cleanup: True
    auto_remove: yes
    #auto_remove: yes
    command: "set_searchengine_secret_key -s {{ searchengine_secret_key }}"
    state: started
    volumes:
    - "{{ apps_folder }}/searchengine/searchengine/:/etc/searchengine/"
  changed_when: false

- name: configure elastics search password
  become: yes
  community.docker.docker_container:
    image: "{{ searchengine_docker_image }}"
    name: elastics_password
    cleanup: True
    auto_remove: yes
    #auto_remove: yes
    command: "set_elasticsearch_password -e {{ ELASTIC_PASSWORD }}"
    state: started
    volumes:
      - "{{ apps_folder }}/searchengine/searchengine/:/etc/searchengine/"
  changed_when: false

- name: configure elastics redis url
  become: yes
  community.docker.docker_container:
    image: "{{ searchengine_docker_image }}"
    name: redis_url
    cleanup: True
    auto_remove: yes
    #auto_remove: yes
    command: "set_redis_url -r {{ REDIS_URL }}"
    state: started
    volumes:
      - "{{ apps_folder }}/searchengine/searchengine/:/etc/searchengine/"
  changed_when: false

# automatic refreshing  when configuration change is detected

- name: Set automatic refreshing the configuration
  become: yes
  community.docker.docker_container:
    image: "{{ searchengine_docker_image }}"
    name: elastics_password
    cleanup: True
    auto_remove: yes
    command: "set_automatic_refresh -a {{ automatic_refresh }}"
    state: started
    volumes:
      - "{{ apps_folder }}/searchengine/searchengine/:/etc/searchengine/"
  changed_when: false

- name: Run docker searchengine  test create index -r image1
  become: yes
  community.docker.docker_container:
    image: "{{ searchengine_docker_image }}"
    name: searchengine_test_create_index
    cleanup: True
    auto_remove: yes
    command: "create_index -r image1"
    networks:
    - name: searchengine-net
    #restart: "{{ searchengine_conf_status | changed }}"
    state: started
    volumes:
      - "{{ apps_folder }}/searchengine/searchengine/:/etc/searchengine/"
  when: not container_info_searchengine_f.exists

#- name: Prune configured docker container to free resources
#  community.docker.docker_prune:
#    containers: true
#    images: true
#    images_filters:
#      dangling: false
#    networks: true
#    volumes: true
#    builder_cache: true
#  changed_when: false

- name: Run docker searchengine
  become: yes
  community.docker.docker_container:
    image: "{{ searchengine_docker_image }}"
    name: searchengine
    cleanup: True
    command: "run_app {{ searchengineurlprefix }}"
    networks:
    - name: searchengine-net
    published_ports:
    - "5577:5577"
    #restart: "{{ searchengine_conf_status | changed }}"
    state: started
    restart_policy: always
    volumes:
      - "{{ apps_folder }}/searchengine/searchengine/:/etc/searchengine/"
      - "{{ apps_folder }}/searchengine/searchengine/cachedata:/etc/searchengine/cachedata"
      - "{{ apps_folder }}/data_dump:/data/data_dump"
  when: not container_info_searchengine_f.exists

- name: Run docker celery job (Synchronize queries)
  become: yes
  community.docker.docker_container:
    image: "{{ searchengine_docker_image }}"
    name: searchengine_celery
    cleanup: True
    command: "celery"
    networks:
    - name: searchengine-net
    state: started
    restart_policy: always
    volumes:
      - "{{ apps_folder }}/searchengine/searchengine/:/etc/searchengine/"
      - "{{ apps_folder }}/searchengine/searchengine/cachedata:/etc/searchengine/cachedata"
      - "{{ apps_folder }}/data_dump:/data/data_dump"
  when: not container_info_searchengine_f.exists

- name: Run docker searchengine run celery beat
  become: yes
  community.docker.docker_container:
    image: "{{ searchengine_docker_image }}"
    name: searchengine_celery_beat
    cleanup: True
    command: "beat"
    networks:
    - name: searchengine-net
    #restart: "{{ searchengine_conf_status | changed }}"
    state: started
    restart_policy: always
    volumes:
      - "{{ apps_folder }}/searchengine/searchengine/:/etc/searchengine/"
      - "{{ apps_folder }}/searchengine/searchengine/cachedata:/etc/searchengine/cachedata"
      - "{{ apps_folder }}/data_dump:/data/data_dump"
  when: not container_info_searchengine_f.exists